package ar.edu.unlu.Chinchon.Juego;


public enum EventosChinchon {
	JUEGO_INICIADO,
	PUNTOS_CAMBIADOS,
	FIN_JUEGO, VER_TOP, CARGAR_JUEGO, JUGADOR_AGREGADO, DESCARTE_VACIO, CARTAS_MAXIMAS, JUGADORES_MAXIMOS, FALTA_UNO, FALTAN_DOS, CARTA_ROBADA, CARTA_TIRADA, TURNO_CAMBIADO, CARTA_ROBADA_DESCARTE, DEBE_ROBAR, MISMO_NOMBRE,
}
